name: Vercel Deploy

on:
  workflow_call:
    inputs:
      is_prod:
        description: 'Indicates if the deployment is for production'
        required: false
        default: 'false'
        type: boolean
    outputs:
      vercel_url:
        description: 'The URL of the deployed preview on Vercel'
        value: ${{ steps.deploy_preview.outputs.vercel_url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      vercel_url: ${{ steps.deploy_preview.outputs.vercel_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy_preview
        run: |

          if [ "${{ inputs.is_prod }}" = "true" ]; then
            echo "Deploying to production environment"
            vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
            url=$(vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm)
          else
            echo "Deploying to preview environment"
            url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --confirm)
          fi


          echo "Vercel URL: $url"
          echo "vercel_url=$url" >> $GITHUB_OUTPUT
