on:
  workflow_call:

jobs:
  run-checks:
    name: 🧪 Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint checks
        run: npm run check:lint
      - name: Run prettier checks
        run: npm run check:prettier
