name: Default CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: 🧪 Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

  lighthouse:
    name: 🚦 Audit Lighthouse
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI on deployed site
        run: lhci autorun --collect.url=https://mathieusteinmetz.vercel.app || echo "Ignore LHCI exit code"
