name: Default CI Workflow
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  test:
    name: 🧪 Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit
  deploy-preview:
    needs: test
    uses: ./.github/workflows/components/vercel-deploy.yml
    with:
      is_prod: true
  generate_lighthouse_audit:
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit preview URL with Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ needs.deploy-preview.outputs.vercel_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const manifest = JSON.parse(`${{ steps.lighthouse_audit.outputs.manifest }}`);
            const links = JSON.parse(`${{ steps.lighthouse_audit.outputs.links }}`);

            const result = manifest[0].summary;
            const formatResult = (res) => Math.round((res * 100))
            Object.keys(result).forEach(key => result[key] = formatResult(result[key]))
            const score = res => res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴'
            const comment = `
            ⚡️ [Lighthouse report](${Object.values(links)[0]}) for the changes in this PR:
            | Category | Score |
            | --- | --- |
            | ${score(result.performance)} Performance | ${result.performance} |
            | ${score(result.accessibility)} Accessibility | ${result.accessibility} |
            | ${score(result['best-practices'])} Best practices | ${result['best-practices']} |
            | ${score(result.seo)} SEO | ${result.seo} |
            *Lighthouse ran on [${Object.keys(links)[0]}](${Object.keys(links)[0]})*`
             return comment;
      - name: Add comment to PR
        id: comment_to_pr
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: lighthouse
          message: |
            ${{ steps.format_lighthouse_score.outputs.result }}
