name: Default CI Workflow
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [main]

jobs:
  checks:
    name: 🧪 Check all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint checks
        run: npm run check:lint

      - name: Run prettier checks
        run: npm run check:prettier

      - name: Run tests
        run: npm run test:unit
  deploy-prod:
    needs: checks
    uses: ./.github/workflows/vercel-deploy.yml
    secrets: inherit
    with:
      is_prod: 'true'
