name: Default CI Workflow
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches: [main]

jobs:
  tests:
    uses: ./.github/workflows/unit-tests.yml
  deploy-prod:
    needs: tests
    uses: ./.github/workflows/vercel-deploy.yml
    secrets: inherit
    with:
      is_prod: 'true'
